print("I Will Miss You")
input()
print("Once upon a time there was a girl named Lua, she is 19 years old and she really likes to party, one day she was at a party and…")
input()
print("Jack:Hello my name is jack")
input()
print("Lua:Hi, I'm Lua. Nice to meet you.")
input()
print("Jack:Do you want to go for a drink or do you want to go dancing?")
input()
option= input("I want to:")
if(option=="drink"):
  input("Jack:bring us 2 margaritas")
  input()
  input("Lua:and what are you studying jack?")
  input("Jack:I'm studying business administration so I can run my dad's business.") 
  input ("Lua:that's good")
  input ("Jack:and you lua?")
  input ("Lua:I am studying chef because that has always been my dream")
if(option=="dance"):
  input("Lua:hey i love this song")
  input("Jack:really!? that's my favorite song")
  input("Lua:hahaha")
  input("*they dance together*")
print("*incoming call to Jack's phone*")
print("Jack: lua I'm so sorry but I have to go, nice to meet you")
input()
print ("Lua: bye Jack, hey Jack what is your instagram!?")
input()
print ("But Jack didn't listen to lua and left")
input("Lua was no longer having a fun time at the party, so she takes a taxi and goes to her house, she gets ready to sleep and lies on her bed and stares at the phone until she falls asleep .")
input ()
print ("Lua wakes up and sees notifications on her phone, she opens them and sees a message from an unknown account.")
print("Message: Hello Lua I'm Jack!")
input ()
print ("Message: How are you? I'm sorry for leaving you like that ")
print("Lua didn't know what to answer or not")
option= input("Answer yes or no:")
if(option=="yes"):
  input ("Lua's message: hello, nothing happens")
  input("Jack's message: and about what time did you get back?")
  input("Lua's message: I came back about 30 minutes after you left, I wasn't having such a great time")
  input("Jack's message: how do you think hahaha")
  input("Jack's message: hey I would like to invite you for a coffee like in the afternoon,do you want to go?")
if(option=="no"):
  input("Lua was very hungry and she made herself some breakfast but out of nowhere she got another")
  input("Jack's message: hey I would like to invite you for a coffee like in the afternoon, do you want to go?")
print("Lua didn't know what to say so she called her best friend Mar.")
input()
print("Lua: Hello Mar")
input()
print("Mar: Hi")
input()
print("Lua: Guess what! yesterday I was at a prty and I met a very cute boy and we have a very good time.")
input()
print("Mar: aha")
input()
print("Lua: but out of nowhere they called him and he had to go and now he's asking me if I want to go have a coffee with me.")
input()
print("Mar: well I don't know if it would be good if you accompanied him because you just met him")
input()
print("Lua: but he is very cute and cool")
input()
print("Mar: well but are you sure you want to go?")
input()
option= input("Answer yes or no:")
if(option=="yes"):
  input("Lua: yes, yes I want to go")
  input("Mar: ok, you say yes but you need to choose a place near your house and send me your location")
  input ("Lua: okk seems very good to me")
  input("Lua: bye")
  input("Mad:bye")
  input ("Lua grabs her phone and answers Jack")
  input ("Lua's message: hello Jack, yes, let's go for a coffee at starbucks")
  input("Jack's message: Wuu, let's go at 5, what do you think?")
  input("Message from lua:okk")
  input("Jack's message: ok, see you there")
  input ("lua's message: bye")
if(option=="no"):
  input("Lua: no, the truth is that I don't want to")
  input("Mar: don't worry, we better go to a coffee, you and I go")
  input ("Lua: okk, at 5 is good ?")
  input("yes")
  input ("lua:bye")
  input ("mar:bye")
  input("Lua grabs her phone and answers Jack")
  input("Lua's message: hello Jack, hey I can't go, sorry ")
  input ("Jack's message: oh, nooo how do you think, go please I liked you very much and I want to know you more")
  input ("Lua's message: well I'm going")
  input ("Jack's message: yes! I'll wait for you!")
  input("Lua sends a message to Mar and tells her...")
  input("Lua's message: Marrr, you know better if I go with Jack")
  input ("Mar's message: okay, but can you send me your location")
  input("Message from lua:yes yes")
input()
print ("Lua started putting on her makeup to go have coffee with Jack, then she ironed her hair, Lua didn't know what to wear, she had 2 ideas.")
print("The first option was white pants with a pink top and the second option was a beige dress.")
option= input("Which option should be put?, first or second:")
if(option=="first"):
  input:("omg i look so pretty")
if(option=="second"):
  input:("omg i look so pretty,I'm going to wear sneakers so it doesn't look so formal.")
input()
print ("Lua walked away since it was very close to her house.")
input()
print ("Jack they are already waiting for her there a little nervous")
input ()
print ("*lua enters and goes with Jack*")
input ()
print("Jack: hi lua")
input ()
print ("Lua: hello")
input ()
print ("Jack: How cute you look")
input ()
print ("Lua: thank you very much")
input ()
print ("Jack: What do you want to order?")
input ()
print ("Lua: I feel like a matcha late and you?")
input ("Jack: to me an American coffee, hey sorry for leaving like that the other day")
print ("Jack: is that my sister call me and he told me that his bag had been stolen")
input ()
print ("Lua: omg , but is your sister okay?")
input ()
print ("Jack: yes she is fine")
input ()
print ("Lua: Good")
input ()
print ("Jack: and how old are you?")
input()
print ("Lua: I'm 20 but I'll be 21 on June 6, in a short time")
print ("Lua: and how old are you?")
input ()
print ("Jack: I'm 22")
print ("Jack: and what are you going to do on your birthday?")
input ()
print ("Lua: I still don't know what to do, but I think I'm going to have dinner with my friends.")
input ()
print ("Jack: That's nice, but you're going to invite me, right?")
input ()
print ("Lua: hahah of course yes")
input ()
print ("*They spend a lot of time talking*")
input ()
print ("Lua: oh my God it's too late")
input ()
print ("Jack: I hadn't realized the time, well I think we already paid right?")
input()
print ("Lua: yesyes , join in the account")
input()
print ("starbucks ticket:")
print ("Matcha latte….$45")
print ("American coffee…$30")
print ("Bagel…$80")
print ("Croissant…$70")
print("Blueberry muffin…$50")
print ("Total=")
input ()
print ("*To achieve the total you have to put the prices of each one*")
n1 = int(input("Put the price of the matcha latte"))
n2=int(input ("Put the price of American coffee"))
n3=int(input ("Put the price of the bagel"))
n4=int(input ("Put the price of the croissant"))
n5=int(input ("put the price of the croissant"))
sum = n1+n2+n3+n4+n5
print ("el total es:",sum)
input ()
print ("Jack: oh okay,now I will pay")
input ()
print ("Lua: it wasn't that much, I thought it was going to be more")
input ()
print ("Jack: yes, me too")
input ()
print ("Lua: well, thank you very much for asking me out")
print ("I had an amazing time")
input ()
print ("Jack: no, thanks to you for accepting")
print ("you are an amazing girl")
input ()
print ("Lua: thanks")
print ("let's see when we meet again")
input ()
print ("Jack: yes, there we send messages")
input()
print ("lua: okey")
input ()
print ("*everyone goes home very happy*")
input()
print ("Lua was super happy")
input ()
print ("Lua: Jack is an amazing guy, I hope to go out with him again")
print ("Oh but it's too late now I have to sleep because I have school tomorrow")
input ()
print ("Lua put on pajamas, brushed her teeth and face and fell asleep")
input ()
print ("*alarm clock*")
input ()
print ("Lua woke up and checked her phone and saw that Jack sent her a message")
print ("Jack's message: Hello lua, good morning")
input ()
print ("Lua didn’t answer the message because she was going to be late")
print ("She had breakfast and she put on her uniform")
input ()
print ("She didn't know what to do, order a taxi or walk")
input ()
print ("What will lua do? ")
option= input("taxi or walk?:")
if(option=="taxi"):
  input ("Lua: hey taxi")
  input  ("Can you take me to chef school please")
  input ("Taxi: yes of course get on")
  input ("Hey, there's a bit of traffic, we'll take a while.")
  input ("Lua: oh no, no way")
  input ("*lua arrives at school*")
  input ("Teacher: lua you are late")
  input ("Lua: sorry there was a lot of traffic")
if(option=="walk"):
  input ("Lua: well I need walk a little faster to get there")
  input("And it's good that I didn't go by taxi, there is a lot of traffic")
  input ("*lua arrives at school*")
  input("Teacher: good morning lua")
  input ("Lua: good morning teacher")
input ()
print ("Teacher: ok, I'm going to start with the class")
input ()
print ("Lua remembers the message that Jack sent her and answers it")
input ()
print ("Lua's message: Hello jack")
print ("good morning")
input ()
print ("lua's message: sorry for not replying to your message")
print ("i was late for school")
input ()
print ("Jack's message:don’t worry")
print ("how are you?")
input ()
print ("But suddenly")
input ()
print ("Teacher: Lua get out of my class")
input ()
print ("Lua: no teacher why?")
input ()
print ("Teacher: you are on the phone")
input ()
print ("go out!")
input ()
print ("Lua leaves her class and goes to the cafeteria")
input ()
print ("Mar her, best friend arrives and sits down with lua and starts asking her about Jack")
input ()
print ("Lua with emotion tells him everything that has happened")
input ()
print ("Then Mar gets excited for Lua and is happy that Lua is happy.")
input ()
print ("*Days go by and Lua and Jack keep talking and going out*")
input ()
print ("Lua is very much in love with Jack and Jack with her but Lua is waiting for Jack to take the next step but Lua feels that she is not going to do it")
input ()
print ("until one day Jack invites her to a special place")
input ()
print ("Jack: Hi Lua")
input ()
print ("Jack: hey let's go to the park")
input()
print("okey ")
input ()
print ("*lua and jack arrive at the park*")
input ()
print ("Jack: lua the truth I love you very much and you are an incredible person and I want to tell you")
input ()
print ("Do you want to be my girlfriend?")
input ()
print ("*jack gives her a bouquet of flowers*")
input ()
print ("Lua: aww so cute")
print ("Yes, I want")
input ()
print ("*after they kiss and go to eat at a restaurant*")
input ()
print ("Lua: Jack I love you so much")
input ()
print ("Jack: me too!")
input ()
print ("* Lua arrives at her house and calls her friend *")
input ()
print ("Lua: hello mar")
input ()
print ("Mar: hello")
input ()
print ("Lua: Guess what!")
input ()
print ("Mar: what!")
input ()
print ("Lua: Jack in my new boyfriend!")
input ()
print ("Mar: OMG")
print ("How?")
input ()
print ("Lua: she invited me to the park, she asked me and she gave me a bouquet of flowers")
input ()
print ("Mar: WOW!")
print ("Good, I'm happy for you")
input ()
print ("lua: thanks")
print ("well I have to sleep bye.")
input ()
print ("Mar: bye!")
input ()
print ("The holidays arrive and Lua and Jack are happy being boyfriends, they go everywhere together and talk to each other every day")
input ()
print ("Until one day…")
input ()
print ("Lua: hey do you want to go out today?")
input ()
print ("Jack: better come to my house")
print ("I have to tell you something very important")
input ()
print ("Lua: ok, what time?")
input ()
print ("Jack: at 4:00 p.m.")
input ()
print ("Lua started to get ready and left her house and took a taxi to go to Jack's house")
input ()
print ("Lua: hey!")
input ()
print ("jack: hello")
input ()
print ("*The two sat in the living room*")
input ()
print ("Jack: lua I have to tell you something very important")
input ()
print ("Lua: What happened?")
input ()
print ("Jack: The thing is, about 6 months ago I applied for a job.")
input()
print ("Lua: good!")
print ("And they gave it to you?")
input ()
print ("Jack: yes")
input ()
print ("Lua: very well we have to celebrate!")
input ()
print ("Jack: no wait")
print (" the point is that the job is in Spain")
input ()
print ("Lua: it's very far")
print ("But when are you leaving?")
input ()
print ("jack: this wednesday")
input ()
print ("Lua: it's in two days")
print ("I do not want you to go")
print ("But it's better for you, and I know you'll be happy there so I think I'll let you go")
input ()
print ("Jack: thanks for understanding")
input ()
print ("*lua returns to her house and starts crying*")
input ()
print ("*lua returns to her house and starts crying*")
input ()
print ("The day arrives and the two agree to meet at the airport")
input ()
print ("Jack: lua!")
input ()
print ("Lua: Jack I'm going to miss you so much")
input ()
print ("Jack: me more!")
input ()
print ("Lua: bye")
input ("Jack: I love you.")